name: build-and-test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: ${{ 'pull_request' != github.event_name || (github.event.pull_request.head.repo.git_url != github.event.pull_request.base.repo.git_url) }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: liberica@1.8

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install numpy
          pip install sklearn
          sudo apt-get -y install aspell

      - name: Build
        run: sbt -v update compile test:compile "test:runMain org.nlogo.models.ExtensionInstaller"

      - name: Test 2D
        run: sbt -v -Dorg.nlogo.onLocal=false test

      - name: Test 3D
        run: sbt -v -Dorg.nlogo.onLocal=false -Dorg.nlogo.is3d=true test

      - name: Failure Debug Info
        if: ${{ failure() }}
        run: |
          pwd
          sudo apt-get -y install tree
          tree
